### ISSUE TITLE
Qt5 runtime errors

### ISSUE THREAD

**Issue by saweiss** [openfoxwq/openfoxwq#2]
After running `openfoxwq_qtclient` on Linux, I get the following runtime errors (and the GUI freezes):
```
QMetaObject::connectSlotsByName: No matching signal for on_ws_connected()
QMetaObject::connectSlotsByName: No matching signal for on_ws_disconnected()
QMetaObject::connectSlotsByName: No matching signal for on_ws_msg(QByteArray)
WebSocket disconnected
```
I don't do much Qt programming, but searching says that you shouldn't use name-based auto connection for slots.

**Comment by ale64bit** [comment]
The ones about `no matching signal (...)` are harmless. I get those as well. Apparently they are due to the [slot naming](https://forum.qt.io/topic/102143/safe-to-ignore-no-matching-signal-for/11), which is rather silly.

Typically frozen UI at login means that the server binary is not running. Namely, you need to run `openfoxwq_wsserver` _before_ running `openfoxwq_qtclient`. Was the server running? And if so, can you share the logs?

I added some more usage instructions in the [release notes](https://github.com/openfoxwq/openfoxwq/releases/tag/v0.1-alpha).

**Comment by ale64bit** [comment]
I renamed the slots so that the warning goes away. Also added some more explicit message about connecting to the local server. Let me know if the problem persists.

**Comment by saweiss** [comment]
Thanks! It's working now. It might be helpful to describe how to run the program in the readme. Or even better, it would be nice to have a single executable that runs the server in the background and opens the GUI.

**Comment by ale64bit** [comment]
> Thanks! It's working now. It might be helpful to describe how to run the program in the readme. 
Definitely. I added some usage instructions in the release notes. But there's no proper documentation per se.

> Or even better, it would be nice to have a single executable that runs the server in the background and opens the GUI.
I agree. Initially, I didn't plan to write a UI at all since I don't have much experience. But I didn't like the native GUI frameworks available in Go and I was hoping that someone with better skills could help in that front or even adapt an existing tool.
